version: 2
updates:
  - package-ecosystem: "gradle"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "bobeal"
    open-pull-requests-limit: 10

