source 'https://rubygems.org'

group :test do
  gem 'cucumber'
  gem 'capybara-screenshot'
  gem 'poltergeist', ">= 1.4.0"
  gem 'rspec-expectations'
  gem 'mongo'
  gem "bson"
  gem "bson_ext"
  gem 'mechanize'
  gem 'httparty'
  gem 'selenium-webdriver'

end
